### ISSUE TITLE
performance - very slow compared to tsserver

### ISSUE THREAD

**Issue by prabirshrestha** [sourcegraph/javascript-typescript-langserver#331] opened 2017-08-09 06:28 UTC
Even an empty project takes for ever to show completion results. `console.` and `window.` took almost 5 sec but `'hello'.` was immediate. The first time I could expect `console.` to be slow but even the second time I run type `console.` it seems slow. I would had also expected the completion to show as I type `c` in console but the results are so slow that it doesn't show.

![slow](https://user-images.githubusercontent.com/287744/29107815-da9cf5a6-7c90-11e7-8d2d-14e1a675fff9.gif)

**Comment by felixfbecker** [comment] 2017-08-09 15:45
Would be interesting to see a trace for this

**Comment by damieng** [comment] 2017-08-09 17:03
Also seeing this slowness using my Atom plug-in. Does your vim plugin support streaming?  I'm wondering if the non-streaming/partialResults versions are that much slower/stacked behind all the partialResults.

**Comment by prabirshrestha** [comment] 2017-08-09 18:53
It follows strict protocol so no streaming or partial results.

I’m also using stdio on windows.

**Comment by prabirshrestha** [comment] 2017-08-09 19:27
Uploaded the log but don't think it will be useful since it doesn't have timestamp. https://gist.github.com/prabirshrestha/fe19248df64de14260d977c42bcdf16c. Also might be good to include the OS, version and the protocol used in the log. Let me know if you still want me to share vim-lsp log which is more verbose.

vim-lsp doesn't support streaming and this could be the root cause of why the completion is being ignored and not shown. Tailing the log I do see partial results come fast.

Given that stream still hasn't been merged to the official protocol I would want to avoid implementing stream in vim-lsp as I would like to get other features first. I also want to avoid writing JSON patch in viml for now.

> Support for this method is indicated by the streaming capability in both ClientCapabilities and ServerCapabilities.

https://github.com/sourcegraph/language-server-protocol/blob/streaming/protocol.md#partialResult

Based on the above spec currently when vim-lsp passes `capabilities: {}` it shouldn't return `partialResults`. So this would still be a bug in lang server.

**Comment by damieng** [comment] 2017-08-09 21:16
The sending of partialResults when not supported by the client has an issue at https://github.com/sourcegraph/javascript-typescript-langserver/issues/329

**Comment by felixfbecker** [comment] 2017-08-10 01:21
Before we jump to conclusions, can you try to comment out this line and see if it changes anything?
https://github.com/sourcegraph/javascript-typescript-langserver/blob/fe72524436ad49f244932bca01dc075991955871/src/connection.ts#L261

**Comment by damieng** [comment] 2017-08-10 01:29
I actually have a patch on mine that puts a if (streaming) block around there.  It stops the partialResults sending but it still takes a long time to process.

I have in my small 1 javascript project a `const path = require('path')` a few lines later in a method I typed `path.` and saw the textDocument/completion request go out. 

It took almost 14 seconds to receive the 31 item array back for the path import.  (This was on my mac)

**Comment by damieng** [comment] 2017-08-10 01:34
Just did some more testing. I think what's happening is that firing the autocomplete for every keystroke is causing a backlog as the scope for that is wide.  If i turn off autocomplete-on-keypress and then just manually trigger the autocomplete request manually performance is much better.

**Comment by felixfbecker** [comment] 2017-08-10 01:35
Does neovim look at the `isIncomplete` value? If it's `false`, it shouldn't send more requests

**Comment by damieng** [comment] 2017-08-10 01:37
Sorry, I'm using my Atom bridge not neovim. We're sending a fresh request for completion on every keystroke effectively. (so it provides autocomplete for variable names etc).

**Comment by tomv564** [comment] 2017-08-10 16:08
I turned off completion on all keystrokes, just have it on what the server advertises ('.'). Is there debouncing logic on your keystroke trigger?

**Comment by prabirshrestha** [comment] 2017-08-10 22:19
I can try @felixfbecker suggestion tonight on commenting partial requests and verify.

I'm using asyncomplete.vim with vim-lsp to provide autocompletion for lang server. It doesn't send completion requests on every keystroke. It does respect `isIncomplete` flag and will only make requests if it is `true`.

asyncomplete.vim and nvim-completion-manager uses  similar algorithm as VsCode for autocomplete which I have written about it at https://github.com/roxma/nvim-completion-manager/issues/30#issuecomment-283281158. It is really good at caching. Might be atom plugin could implement similar algorithm? There is also an active issue on LSP on how `triggerCharacters`. https://github.com/Microsoft/language-server-protocol/issues/268

I also have written my own implementation of the typescript language server that acts as a proxy for `tsserver.cmd` which I will try to open source tonight. Currently only implemented `textDocument/completion`. I didn't have any issues with the perf there even for large codebase.

**Comment by damieng** [comment] 2017-08-10 22:57
Drastically reducing how often we called completion has solved problems on Atom. Now we just trigger it on . and when manually requested.

**Comment by prabirshrestha** [comment] 2017-08-11 06:54
Here is the language server implemented as proxy for `tsserver` https://github.com/prabirshrestha/typescript-language-server. README.md has details on how to get started. Currently it only supports completionProvider. @damieng can you try and see if this one is faster?

@felixfbecker I commented the line you showed and now the completions shows up correctly but the perf is still slower compared to `typescript-language-server`.

**Comment by felixfbecker** [comment] 2017-08-11 23:48
I added a command line flag and docs to make it easy to spin up a Jaeger instance with one command to debug performance issues. This gives you a trace view in your browser on localhost like this:

**Comment by tomv564** [comment] 2017-08-25 13:50
I hope my tracing is correct:

<img width="1264" alt="screen shot 2017-08-25 at 15 41 12" src="https://user-images.githubusercontent.com/4395832/29716552-0fdae926-89ac-11e7-885a-be0afb5727e4.png">

This is for triggering a word (not member) completion with a single `W` somewhere in typescript-service.ts.

If my tracing is correct, getting completion entry details and converting them to CompletionItems is _very_ expensive. May be worth sending less complete completionItems.

Word completions cause a search over global scope **and appears to not filter by starting character**. So if you have the `dom` lib added to your compilerOptions, you will get lots of stuff like WebAuthentication and WebGL*.

I'll push my tracing changes to a branch if someone can review. Also, how can I trace the gap between `ensureModuleStructure` and the actual completion handling?

**Comment by felixfbecker** [comment] 2017-08-25 18:11
That's an interesting find. This can probably be solved by implementing `completionItem/resolve` to resolve the expensive details.

> Also, how can I trace the gap between ensureModuleStructure and the actual completion handling?

That means there is some function call in between these that does not create a child span or is not passed a parent span. In recursive functions I don't pass them after the first level to not clutter the traces, but for development you can change the code to pass them.

**Comment by tomv564** [comment] 2017-08-25 22:11
This tracing functionality makes for fun investigations!

Like the above trace, I restarted the server, created some newlines in the document and waited for diagnostics, and then pressed `W`.

Without completion item details:

<img width="1270" alt="screen shot 2017-08-25 at 22 26 33" src="https://user-images.githubusercontent.com/4395832/29732079-558ba1d2-89e7-11e7-8698-4a5f1c6cce6b.png">

Without completion item details and without `ensureReferencedFiles`:

<img width="1264" alt="screen shot 2017-08-25 at 22 45 57" src="https://user-images.githubusercontent.com/4395832/29732085-5bee4548-89e7-11e7-9898-40c4839911cc.png">

Also without `ensureBasicFiles`:

<img width="1271" alt="screen shot 2017-08-25 at 22 53 39" src="https://user-images.githubusercontent.com/4395832/29732414-cc184ba6-89e8-11e7-9f08-c9a4d57ca931.png">

Also with `dom` removed from libs in tsconfig.

<img width="1268" alt="screen shot 2017-08-25 at 22 57 02" src="https://user-images.githubusercontent.com/4395832/29732443-ecee19b4-89e8-11e7-814a-fd2c8034710e.png">

Even with completions at 28ms, it is still far from instant because of the preceding didChange -> getProgram -> publishDiagnostics taking up 250ms or more.

```
LSP 23:39:38:645286: requesting for: "W" 1024:4
LSP 23:39:38:646373: notify: textDocument/didChange
LSP 23:39:38:647310: request: textDocument/completion
LSP 23:39:38:883449: got json: textDocument/publishDiagnostics
JSTS 23:39:38:905401: getCompletions for /Users/tomv/Projects/sourcegraph/javascript-typescript-langserver/src/typescript-service.ts contents "			W" position 4
LSP 23:39:38:905903: got json:  result":{"isIncomplete":false,"items":
```

Making the client resolve completion details sounds like a clear win - we might lose member types in completion lists however. Perhaps VS code has some clever way of managing this.

Even after stripping down the work done in textDocumentCompletions the completions continued to work. 

Can we eliminate some of the `ensures` because a client should have called `didChange` before the completion request?

Can we defer publishDiagnostics? (even if it doesn't cost much, the client would likely prefer receiving completions before diagnostics)

**Comment by felixfbecker** [comment] 2017-08-25 22:57
Glad it's helpful, invested a lot of time into it!

> Making the client resolve completion details sounds like a clear win - we might lose member types in completion lists however. Perhaps VS code has some clever way of managing this.

We only need the name and kind upfront. Docs and details are resolved when the completion is selected.

> Can we eliminate some of the ensures because a client should have called didChange before the completion request?

That's not given. You can get completion on a non-changed file. But more importantly, you need the dependent files. I would look into doing more memoization in the recursive ensure calls.

> Can we defer publishDiagnostics? (even if it doesn't cost much, the client would likely prefer receiving completions before diagnostics)

Totally, the diagnostics publisher can act as a queue to push diagnostics into and publish them debounced (eliminating overriding diagnostics).

**Comment by epeli** [comment] 2017-09-04 14:45
I can confirm that the performance goes up a lot when when `dom` is removed from the `compilerOptions.lib` array in `tsconfig.json`. I'm using Neovim and [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim)

**Comment by felixfbecker** [comment] 2017-09-08 11:13
Please confirm if this is still a problem with v2.3.1

**Comment by damieng** [comment] 2017-11-05 21:15
The new completionItems are now basically just a kind, a label and a sort.   The experience is very compromised and the list nowhere near as useful.  Was there no middle ground?

**Comment by felixfbecker** [comment] 2017-11-06 02:54
@damieng does your client call `completionItem/resolve`?

**Comment by damieng** [comment] 2017-11-06 03:21
Not yet but it's my understanding that clients call that as the user highlights the option (e.g. cursor up.down) or actually resolves it.

For a drop-down list not seeing arguments for each entry really cuts down the usefulness.

**Comment by felixfbecker** [comment] 2017-11-06 03:22
Sorry, not sure what you mean / whether that is intended or a bug. Could you elaborate a bit what is expected and actual? Maybe a screenshot?

**Comment by damieng** [comment] 2017-11-06 19:56
This is what we used to be able to achieve;

![image](https://user-images.githubusercontent.com/118951/32460892-0de91d74-c2e9-11e7-9ac5-b38683cb07f3.png)

Since the change in 2.3.0 now all we can do is this;

![image](https://user-images.githubusercontent.com/118951/32461040-7334e262-c2e9-11e7-8f86-0bd6b22220eb.png)

Yes, I know you can get extra detail from the resolve call but that's only supposed to be if you confirm a selection or go through the list with cursor keys unless I'm mis-reading the spec?  i.e. it makes sense for doc params but definitely not for details that affect the initial rendering of the list like details of parameters and return types?

**Comment by felixfbecker** [comment] 2017-11-06 20:05
@damieng seems like VS Code and Atom behave differently here, VS Code will only show the "details" for the selected item:

![image](https://code.visualstudio.com/assets/docs/editor/intellisense/intellisense_docs.gif)

https://code.visualstudio.com/docs/editor/intellisense

So I assume VS Code will call `completionItem/resolve` for the selected item.

In your screenshot, `B` is selected, so shouldn't that show the details by calling `completionItem/resolve`? Is that a bug in the client? Could you verify that `completionItem/resolve` is being sent?

Given that the details are expensive to calculate, I would propose that if Atom users want to see the details for _all_ completion items (not only the selected) Atom adds a setting to call `completionItem/resolve` not just for the selected item but for all visible items. That way we only have to do this computation for the items that are actually visible (e.g. 10) instead of for the whole list (e.g. 1000)

**Comment by damieng** [comment] 2017-11-06 20:38
I personally think the experience there in VSCode is terrible. If you are looking for a method that takes a particular object then you have to try every single one.  It's certainly not on part with other IDE's such as full Visual Studio or Intelli-J.

Right now we don't have the necessary hooks in our autocomplete package necessary to invoke resolve either on selection or for all currently visible :(

**Comment by felixfbecker** [comment] 2017-11-06 21:18
The problem is that sending back all data would take us back to the performance problem again, and I think we definitely do not have to resolve the details for the whole list, it should only be for the visible or selected (whatever the client prefers). Unfortunately there is no `ClientCapability` for `completionItem/resolve` so we can't have different behaviour either, and implementing that might take just as long anyway as implementing `completionItem/resolve` in Atom. It has been part of the spec for quite a while after all. If you care about this a lot you could rollback to the version before we added support for it in the server, but I think the best path forward is getting support in Atom or you'll meet these problems with other language servers too eventually.

I'm gonna close this issue as I believe the perf issue was solved but if you meet any problems with `completionItem/resolve` feel free to open a new issue.

**Closed by felixfbecker** 2017-11-06 21:18 UTC
Labels: needs more info, perf

**Comment by maxbrunsfeld** [comment] 2017-11-06 22:40
> Unfortunately there is no ClientCapability for completionItem/resolve so we can't have different behaviour either, and implementing that might take just as long anyway as implementing completionItem/resolve in Atom.

@felixfbecker We're definitely going to implement `completionItem/resolve` in Atom, but that doesn't totally solve our problem: we'd like to show the type signatures for all of the initially-visible items right away, not require the user to scroll through the list in order to see them.

It's true that the server doesn't know *exactly* how many items will be initially visible when it gets the `textDocument/completion` request, but it can make a pretty good guess. It's probably not going to be more than 10.

What would you think about adding the ability to eagerly include type signatures for the first `N` completion items, where `N` is configurable somehow, maybe via a command line flag? I get that it adds some complexity, but I think it's really a *huge* improvement from a user's perspective.

**Comment by felixfbecker** [comment] 2017-11-06 22:43
@maxbrunsfeld why not simply call `completionItem/resolve` for the N items? That would work for every language server, not just this one. I don't think there would be a performance overhead as the bottleneck is still resolving the detail and it's actually a good thing to show the user the list first and not block on the details.

**Comment by damieng** [comment] 2017-11-06 22:47
I don't think any of the other language servers we've seen are quite as thrifty with the initial detail provided.

**Comment by tomv564** [comment] 2017-11-07 11:31
Sorry to comment on a closed issue, but I wanted to add some details to help you make a decision:
* All Microsoft's completion implementations for Typescript (including full Visual Studio and Sublime Text) only show label and kind (and request details for a tooltip)). 
* With typescript 2.6  _all exports of the project will show up in non-member completions_, so the cost of converting all to detailed completions will go up even more (https://github.com/Microsoft/TypeScript/pull/19069)
