### ISSUE TITLE
Completion should consider context

### ISSUE THREAD

**Issue by sQVe** [sourcegraph/javascript-typescript-langserver#451] opened 2018-04-30 05:54 UTC
_Cheers for all the work put into the langserver. It opens up major things for us on Vim!_
_______________________

Say you have a file with this content:
```
class Dummy {}

const array = [1,2,3];
```
and you add a line and want to call a method on the `array`. Instead of just getting suggestions that make sense after a `.` you also get global things like `Dummy` etc.

![39410891-86104440-4bff-11e8-889d-019c06d1899e](https://user-images.githubusercontent.com/2284724/39416171-2d9c9b3c-4c4b-11e8-8715-baed5657aaa6.png)

I raised this issue at `LanguageClient-neovim` (https://github.com/autozimu/LanguageClient-neovim/issues/408), but it was closed due to this being a langserver issue.

**Comment by felixfbecker** [comment] 2018-04-30 05:59
This sounds like a duplicate of https://github.com/sourcegraph/javascript-typescript-langserver/issues/432

**Comment by sQVe** [comment] 2018-04-30 06:17
@felixfbecker That issue is a bit all over the place, but sure - they may be related. 

Everything is functioning properly but it is slightly annoying getting suggestions for things that should be suggested.

**Comment by felixfbecker** [comment] 2018-04-30 06:41
I am pretty sure it is the exact same issue (which is a bug in the neovim client).

It's irreproachable in VS Code:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/10532611/39417072-b00ef3d4-4c06-11e8-81ca-7584299515e0.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/10532611/39417077-b58ac36a-4c06-11e8-81f3-acae8c69f425.png">

**Closed by felixfbecker** 2018-04-30 06:41 UTC

**Comment by sQVe** [comment] 2018-04-30 08:29
@felixfbecker You are probably right. I just find it a bit confusing that nvim-typescript doesn't have this issue. But maybe it's wrong of me to compare the two.

Do you know if there is an issue made regarding this in neovim? I could create one if not.

**Comment by felixfbecker** [comment] 2018-04-30 16:39
I assume nvim-typescript is a differnt project, different projects, different bugs ;)

In the linked issue rhere was an issue field that was closed as language server issue, but this should be sufficient proof that ot is _not_ a language server issue.

**Comment by chemzqm** [comment] 2018-04-30 19:58
There is the those items is vscode.
<img width="281" alt="screen shot 2018-05-01 at 3 55 54 am" src="https://user-images.githubusercontent.com/251450/39447222-aca6b2f2-4cf3-11e8-994d-273abcc749fe.png">
The problem is LanguageClient-neovim doesn't consider the order returned from language server, it's using words sort https://github.com/autozimu/LanguageClient-neovim/blob/d7cac79c1dd2b7b644c07ff55c8208821ff1192e/rplugin/python3/deoplete/sources/LanguageClientSource.py#L15

**Comment by sQVe** [comment] 2018-04-30 20:35
@felixfbecker I believe that @chemzqm screenshot above is from VSCode running this langserver though.

**Comment by chemzqm** [comment] 2018-04-30 20:36
@felixfbecker it's just appears at bottom.

**Comment by felixfbecker** [comment] 2018-04-30 20:37
It doesn't for me:

![image](https://user-images.githubusercontent.com/10532611/39448964-964c8374-4c7b-11e8-93db-cc0e84578e72.png)

How did you install the language server into vscode?

**Comment by chemzqm** [comment] 2018-04-30 20:38
@felixfbecker from the extensions tab inside vscode, fresh installed.

**Comment by felixfbecker** [comment] 2018-04-30 20:39
Installed what exactly? Did you disable the built-in TypeScript support?

**Comment by chemzqm** [comment] 2018-04-30 20:40
<img width="880" alt="screen shot 2018-05-01 at 4 39 51 am" src="https://user-images.githubusercontent.com/251450/39449117-c4a13a02-4cf9-11e8-9199-2a61c23f46f6.png">
No, I didn't make any configuration for it.

**Comment by felixfbecker** [comment] 2018-04-30 23:11
That extension is out of date, see:

![image](https://user-images.githubusercontent.com/10532611/39449193-413b09b8-4c7c-11e8-9f01-f0e283e685f7.png)

I just published a new version with the updated language server (I `npm link`'ed it manually before).

Also you need to go to "Show builtin extensions" and disable the integrated TS service.

![image](https://user-images.githubusercontent.com/10532611/39454577-0e32a32c-4c91-11e8-8ace-7f9d8995a60e.png)

![image](https://user-images.githubusercontent.com/10532611/39454592-20fba526-4c91-11e8-8434-9920fb21655c.png)

**Comment by sQVe** [comment] 2018-05-01 16:45
@felixfbecker You were indeed correct. The issue was within the client and how it sorted the completions. It is now fixed and the langserver suggestions are at the top.

If one wants to get rid of all other completions other than the langserver you have to play around with deoplete and it's sources.

**Comment by tom-james-watson** [comment] 2018-11-06 11:06
@sQVe - what excatly did you need to change? I'm using neovim with this setup and can't work out how to hide the non-semantic completion suggestions.

**Comment by sQVe** [comment] 2018-11-06 13:12
@tom-james-watson As far as I remember I had to change something on how the completion `sorted` the `buffer` and `LC` results. When trying to retrace my steps now it seems to work _"out-of-the-box"_ with `deoplete`. I can disable all custom `LanguageServer-neovim` and `deoplete` and it still works.

If you want to see what my current setup looks like for plugin you can check out: https://github.com/sQVe/dotfiles/blob/master/config/nvim/plugins.vim
